version: "3.8"
services:
  php:
    image: secobau/phpinfo:latest
    deploy:
      placement:
        constraints:
        - node.role == worker
      replicas: 1
      resources:
        limits:
          cpus: "0.01"
          memory: 32Mi
        reservations:
          cpus: "0.01"
          memory: 16Mi
    healthcheck:
      interval: 10s
      start_period: 30s
      test: php -r "print file_get_contents('http://localhost:8080/');"
      timeout: 1s
    ports:
    - "30000:8080"
